sudo: false

addons:
  apt:
    packages:
    - luarocks

install:
  - eval $(luarocks path --bin)
  - luarocks install --local luacheck

before_script:
  - /home/travis/.luarocks/bin/luacheck . --no-color -qo "011"

script: curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash

notifications:
  email:
    on_success: never
    on_failure: always

cache:
  apt: true
  directories:
    - $HOME/.luarocks

branches:
  only:
    - /^\d+\.\d+\.\d+(\.\d+)?(-\S*)?$/
